add template for vdr instance
yavdr/yavdr-ansible pull request #23
Opened 2021-08-22 09:26 UTC by kfb77

Please make vdr instance configurable from playbook.
This is my proposal as PR.

2021-11-28 19:51 UTC, seahawk1986 commented
The configuration for yavdr-frontend also needs to be changed, so it will be able to control the vdr with the configured instance id.

`/etc/yavdr-frontend/config.yml`
```yaml
vdr:
    id: 0  # vdr instance id
```

2021-11-28 20:49 UTC, kfb77 commented
I do not have this file, not even the directory /etc/yavdr-frontend.
My system is a RasPi3+ installed from branch focal.
Which role should creates this file ?

2021-11-29 22:02 UTC, seahawk1986 commented
The configuration file is from the `python3-yavdrfrontend` package (which is not installed by the Raspberry Pi playbook since there is no working kodi package). I need to look into changing values in a yaml file while keeping comments - AFAIK https://pypi.org/project/ruamel.yaml/ can do that.

2021-11-30 08:14 UTC, kfb77 commented
PR should normally be complete but I have no other vdr with frontend.
For once, would you add the part yourself ?
If not I habe to wait until the kodi package for RasPi is ready and add it myself.

2021-11-30 11:43 UTC, seahawk1986 commented
Yes, it is on my todo list - I just need to find some time to make the necessary changes ...

2021-11-30 13:44 UTC, seahawk1986 requested changes
The proposed solution for changing vdr-dbus-send does not work because the destination for the interface object does not change.

My plan is as follows:
 * allow vdr-dbus-send to use a VDR_ID environment variable (which can be set on the fly or via `/etc/profile.d/`, the `~/.bashrc`, etc.): https://github.com/flensrocker/vdr-plugin-dbus2vdr/pull/29 - so changing `vdr-dbus-send.sh` (which is not update-safe) is not necessary
 * create an ansible module that allows changing values in yaml files based on ruamel.yaml
 * add a task to update the yavdr-frontend configuration if it exists
 * add the other proposed changes

2021-11-30 13:44 UTC, seahawk1986 commented on roles/vdr/tasks/main.yml
> +    path: /usr/share/vdr-plugin-dbus2vdr/vdr-dbus-send.sh
This won't survive updates for vdr-plugin-dbus2vdr - maybe vdr-dbus-send should source a config file to use a configurable instance id.

2021-11-30 13:44 UTC, seahawk1986 commented on roles/vdr/tasks/main.yml
> +- name: configure dbus for vdr instance "{{ vdr.instance }}"
This does not work because the interface destination name is always `de.tvdr.vdr` - I will propose a change for `vdr-dbus-send` from vdr-plugin-dbus2vdr, that handles this properly - it should look like this:
```shell
#!/bin/bash

declare -i VDR_ID=${VDR_ID:-0}

if [ $# -lt 2 ]
then
  echo "usage: $0 objectpath interface.method [arguments]"
  exit 1
fi

DEST=de.tvdr.vdr
INTERFACE_DEST="$DEST"
(( VDR_ID > 0 )) && DEST+="${VDR_ID}"
OBJECT=$1
shift
INTERFACE=$1
shift

dbus-send --system --type=method_call --dest=$DEST --print-reply $OBJECT $INTERFACE_DEST.$INTERFACE "$@"
````

2021-11-30 14:19 UTC, kfb77 commented
OK, I understand that with my simple approach I am far from a generally working solution.
You can close my PR.

2022-01-11 12:21 UTC, merged

2022-01-11 12:22 UTC, seahawk1986 commented
I found some time to make the neccessary changes - with the new commits it is possible to set a value for vdr.instance_id (see https://github.com/yavdr/yavdr-ansible/blob/focal/group_vars/all#L33) and this value is set for vdr, vdr-addon-avahi-linker, yavdr-frontend and dbus-send.

Please check if this works for you as intended.

2022-01-11 18:19 UTC, kfb77 commented
Thank you very much, it works as intended